# Generated by Django 4.1.5 on 2023-01-20 21:02

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):
    dependencies = [
        ("blogApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=froala_editor.fields.FroalaField(),
        ),
    ]
