name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Install Python dependencies
        run: pip install black
        
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          version: "~= 22.0"
